name: Comments on Issue Newly Created
on:
 issues:
  types: [opened]
jobs:
  comment:
   runs-on: ubuntu-latest
   steps:
    - name: print
      run: echo '${{toJson(github.event)}}' | jq
      shell: bash
    - name: create comment
      uses: peter-evans/create-or-update-comment@v2
      with:
       issue-number: ${{github.event.issue.number}}
       body: |
        Learning GitHub Actions. Testing workflow to trigger on newly created issue.
