name: hello
on:
 push:
  branches:
   - main
 workflow_dispatch:
jobs:
 hello_world: 
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - run: echo "Hello World"
 goodbye_world:
  runs-on: ubuntu-latest
  steps:
    - run: echo "GoodBye World"
 
  
