name: Input Variables
on:
 workflow_dispatch:
  inputs:
   number1:
     description: First Number
     default: '0'
     required: true
   number2:
    description: Second Number
    default: '0'
    required: true
   
jobs:
 add_numbers:
  runs-on: ubuntu-latest
  steps:
   - name: task
     run: echo Addition of two numbers ${{inputs.number1}} and ${{inputs.number2}} is sum::((${{inputs.number1}}+${{inputs.number2}}))
